using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZPrinterConfig.Models
{
    public class ZebraCommands
    {

        public static List<String> GetVarCommands = new List<String>()
        {
            {"alerts.conditions" },
            {"alerts.configured" },
            {"alerts.destinations" },
            {"alerts.http.authentication.entries" },
            {"alerts.http.logging.entries" },
            {"alerts.http.logging.max_entries" },
            {"alerts.http.proxy" },
            {"alerts.tracked_settings.log_tracked" },
            {"alerts.tracked_settings.max_log_entries" },
            {"alerts.tracked_sgds.log" },
            {"alerts.tracked_sgds.max_log_entries" },
            {"apl.enable" },
            {"apl.framework_version" },
            {"apl.version" },
            {"appl.bootblock" },
            {"appl.date" },
            {"appl.link_os_version" },
            {"appl.name" },
            {"appl.option_board_version" },
            {"bluetooth.address" },
            {"bluetooth.afh_map" },
            {"bluetooth.afh_map_curr" },
            {"bluetooth.afh_mode" },
            {"bluetooth.authentication" },
            {"bluetooth.bluetooth_pin" },
            {"bluetooth.date" },
            {"bluetooth.discoverable" },
            {"bluetooth.enable" },
            {"bluetooth.enable_reconnect" },
            {"bluetooth.friendly_name" },
            {"bluetooth.json_config_channel_enable" },
            {"bluetooth.le.controller_mode" },
            {"bluetooth.le.minimum_security" },
            {"bluetooth.le.power_class" },
            {"bluetooth.local_name" },
            {"bluetooth.minimum_security_mode" },
            {"bluetooth.page_scan_window" },
            {"bluetooth.power_class" },
            {"bluetooth.radio_auto_baud" },
            {"bluetooth.radio_version" },
            {"bluetooth.short_address" },
            {"bluetooth.version" },
            {"capture.channel1.data.mime" },
            {"capture.channel1.data.raw" },
            {"capture.channel1.delimiter" },
            {"capture.channel1.max_length" },
            {"capture.channel1.port" },
            {"capture.count" },
            {"card.inserted" },
            {"card.mac_addr" },
            {"comm.baud" },
            {"comm.halt" },
            {"comm.parity" },
            {"comm.pnp_option" },
            {"comm.stop_bits" },
            {"comm.type" },
            {"cradle.comm.baud" },
            {"cradle.comm.handshake" },
            {"cutter.clean_cutter" },
            {"device.allow_firmware_downloads" },
            {"device.allow_non_display_numeric_comparison" },
            {"device.applicator.data_ready" },
            {"device.applicator.data_ready_activation" },
            {"device.applicator.end_print" },
            {"device.applicator.feed" },
            {"device.applicator.media_out" },
            {"device.applicator.pause" },
            {"device.applicator.reprint" },
            {"device.applicator.rfid_void" },
            {"device.applicator.ribbon_low" },
            {"device.applicator.ribbon_out" },
            {"device.applicator.service_required" },
            {"device.applicator.start_print" },
            {"device.applicator.start_print_mode" },
            {"device.applicator.voltage" },
            {"device.bluetooth_installed" },
            {"device.command_override.active" },
            {"device.command_override.list" },
            {"device.company_contact" },
            {"device.configuration_number" },
            {"device.cutter_installed" },
            {"device.download_connection_timeout" },
            {"device.epl_legacy_mode" },
            {"device.feature.802_11ac" },
            {"device.feature.bluetooth_le" },
            {"device.feature.head_element_test" },
            {"device.feature.lighted_arrows" },
            {"device.feature.mcr" },
            {"device.feature.nfc" },
            {"device.feature.ribbon_cartridge" },
            {"device.friendly_name" },
            {"device.frontpanel.feedenabled" },
            {"device.frontpanel.line1" },
            {"device.frontpanel.line2" },
            {"device.frontpanel.xml" },
            {"device.host_identification" },
            {"device.host_status" },
            {"device.idle_display_format" },
            {"device.idle_display_value" },
            {"device.internal_wired_setting_location" },
            {"device.job_log.total_jobs" },
            {"device.jobs_print" },
            {"device.languages" },
            {"device.light.cover_open_brightness" },
            {"device.light.head_open_brightness" },
            {"device.light.media_path_brightness" },
            {"device.light.ribbon_path_brightness" },
            {"device.loader_version" },
            {"device.location" },
            {"device.ltu_installed" },
            {"device.orientation" },
            {"device.pmcu.revision" },
            {"device.pnp_option" },
            {"device.position.accuracy" },
            {"device.position.altitude" },
            {"device.position.latitude" },
            {"device.position.longitude" },
            {"device.print_reprogram_2key" },
            {"device.printhead.odometer" },
            {"device.printhead.test.detail" },
            {"device.printhead.test.summary" },
            {"device.product_name_submodel" },
            {"device.protected_mode" },
            {"device.rewinder_installed" },
            {"device.save_2key" },
            {"device.sensor_profile" },
            {"device.sensor_select" },
            {"device.serial_number.option_board_date" },
            {"device.serial_numbers.applicator_option_board" },
            {"device.serial_numbers.applicator_option_board_date" },
            {"device.serial_numbers.control_panel_date" },
            {"device.serial_numbers.cutter" },
            {"device.serial_numbers.cutter_date" },
            {"device.serial_numbers.ethernet_option_board_date" },
            {"device.serial_numbers.mlb_date" },
            {"device.serial_numbers.parallel_option_board" },
            {"device.serial_numbers.parallel_option_board_date" },
            {"device.serial_numbers.printhead" },
            {"device.serial_numbers.printhead_date" },
            {"device.serial_numbers.processor" },
            {"device.serial_numbers.usb_host_option_board" },
            {"device.serial_numbers.usb_host_option_board_date" },
            {"device.serial_numbers.wired_ethernet_option_board" },
            {"device.set_clock_to_build_date" },
            {"device.slot_1" },
            {"device.slot_2" },
            {"device.super_host_status" },
            {"device.syslog.configuration" },
            {"device.syslog.enable" },
            {"device.syslog.entries" },
            {"device.syslog.log_max_file_size" },
            {"device.syslog.save_local_file" },
            {"device.unique_id" },
            {"device.uptime" },
            {"device.user_p1" },
            {"device.user_p2" },
            {"device.user_vars.userVar1" },
            {"device.xml.enable" },
            {"display.backlight" },
            {"display.backlight_on_time" },
            {"display.batch_counter" },
            {"display.bluetooth.mac" },
            {"display.language" },
            {"display.password.level" },
            {"display.root_wml" },
            {"display.text" },
            {"evice.cpcl_synchronous_mode" },
            {"external_wired.check" },
            {"external_wired.ip.addr" },
            {"external_wired.ip.arp_interval" },
            {"external_wired.ip.default_addr_enable" },
            {"external_wired.ip.dhcp.cid_all" },
            {"external_wired.ip.dhcp.cid_enable" },
            {"external_wired.ip.dhcp.cid_prefix" },
            {"external_wired.ip.dhcp.cid_suffix" },
            {"external_wired.ip.dhcp.cid_type" },
            {"external_wired.ip.gateway" },
            {"external_wired.ip.netmask" },
            {"external_wired.ip.port" },
            {"external_wired.ip.protocol" },
            {"external_wired.ip.timeout.enable" },
            {"external_wired.ip.timeout.value" },
            {"external_wired.ip.v6.addr" },
            {"external_wired.ip.v6.gateway" },
            {"external_wired.ip.v6.prefix_length" },
            {"external_wired.mac_addr" },
            {"external_wired.mac_raw" },
            {"ezpl.head_close_action" },
            {"ezpl.label_length_max" },
            {"ezpl.label_sensor" },
            {"ezpl.media_type" },
            {"ezpl.power_up_action" },
            {"ezpl.print_method" },
            {"ezpl.print_width" },
            {"ezpl.reprint_mode" },
            {"ezpl.tear_off" },
            {"file.capture_response.destination" },
            {"file.cert.expiration" },
            {"file.cert.supported_curves" },
            {"file.dir" },
            {"file.dir_format" },
            {"head.authenticated" },
            {"head.darkness_switch" },
            {"head.darkness_switch_enable" },
            {"head.element_test" },
            {"head.latch" },
            {"head.resolution.in_dpi" },
            {"input.capture" },
            {"interface.network.active.arp_interval" },
            {"interface.network.active.cable_type" },
            {"interface.network.active.dhcp_received_host_name" },
            {"interface.network.active.gateway" },
            {"interface.network.active.ip_addr" },
            {"interface.network.active.mac_addr" },
            {"interface.network.active.mac_raw" },
            {"interface.network.active.netmask" },
            {"interface.network.active.protocol" },
            {"interface.network.active.protocol_error" },
            {"interface.network.active.rx_errors" },
            {"interface.network.active.rx_packets" },
            {"interface.network.active.speed" },
            {"interface.network.active.tx_errors" },
            {"interface.network.active.tx_packets" },
            {"interface.network.active.wins_addr" },
            {"interface.network.server_address" },
            {"interface.network.settings_require_reset" },
            {"internal_wired.8021x.peap.anonymous_identity" },
            {"internal_wired.8021x.peap.validate_server_certificate" },
            {"internal_wired.8021x.private_key_password" },
            {"internal_wired.8021x.security" },
            {"internal_wired.8021x.ttls_tunnel" },
            {"internal_wired.8021x.username" },
            {"internal_wired.activity_led" },
            {"internal_wired.auto_switchover" },
            {"internal_wired.enable" },
            {"internal_wired.installed" },
            {"internal_wired.ip.addr" },
            {"internal_wired.ip.arp_interval" },
            {"internal_wired.ip.default_addr_enable" },
            {"internal_wired.ip.dhcp.arp_verify" },
            {"internal_wired.ip.dhcp.cache_ip" },
            {"internal_wired.ip.dhcp.cid_all" },
            {"internal_wired.ip.dhcp.cid_enable" },
            {"internal_wired.ip.dhcp.cid_prefix" },
            {"internal_wired.ip.dhcp.cid_suffix" },
            {"internal_wired.ip.dhcp.cid_type" },
            {"internal_wired.ip.dhcp.lease.last_attempt" },
            {"internal_wired.ip.dhcp.lease.length" },
            {"internal_wired.ip.dhcp.lease.server" },
            {"internal_wired.ip.dhcp.lease.time_left" },
            {"internal_wired.ip.dhcp.option12" },
            {"internal_wired.ip.dhcp.option12_format" },
            {"internal_wired.ip.dhcp.option12_value" },
            {"internal_wired.ip.dhcp.requests_per_session" },
            {"internal_wired.ip.dns.servers" },
            {"internal_wired.ip.gateway" },
            {"internal_wired.ip.netmask" },
            {"internal_wired.ip.port" },
            {"internal_wired.ip.port_json_config" },
            {"internal_wired.ip.protocol" },
            {"internal_wired.ip.timeout.enable" },
            {"internal_wired.ip.timeout.value" },
            {"internal_wired.ip.wins.addr" },
            {"internal_wired.ip.wins.permanent_source" },
            {"internal_wired.mac_addr" },
            {"internal_wired.mac_raw" },
            {"ip.active_network" },
            {"ip.addr" },
            {"ip.arp_interval" },
            {"ip.bootp.enable" },
            {"ip.dhcp.arp_verify" },
            {"ip.dhcp.auto_provision_enable" },
            {"ip.dhcp.cache_ip" },
            {"ip.dhcp.cid_all" },
            {"ip.dhcp.cid_enable" },
            {"ip.dhcp.cid_prefix" },
            {"ip.dhcp.cid_suffix" },
            {"ip.dhcp.cid_type" },
            {"ip.dhcp.cid_value" },
            {"ip.dhcp.enable" },
            {"ip.dhcp.lease.last_attempt" },
            {"ip.dhcp.lease.server" },
            {"ip.dhcp.lease.time_left" },
            {"ip.dhcp.ntp.enable" },
            {"ip.dhcp.ntp.received_servers" },
            {"ip.dhcp.option12" },
            {"ip.dhcp.option12_format" },
            {"ip.dhcp.option12_value" },
            {"ip.dhcp.request_timeout" },
            {"ip.dhcp.requests_per_session" },
            {"ip.dhcp.session_interval" },
            {"ip.dhcp.user_class_id" },
            {"ip.dhcp.vendor_class_id" },
            {"ip.dns.domain" },
            {"ip.dns.servers" },
            {"ip.firewall.whitelist_in" },
            {"ip.ftp.enable" },
            {"ip.ftp.execute_file" },
            {"ip.ftp.request_password" },
            {"ip.gateway" },
            {"ip.http.admin_name" },
            {"ip.http.admin_password" },
            {"ip.http.custom_link_name" },
            {"ip.http.custom_link_url" },
            {"ip.http.enable" },
            {"ip.http.faq_url" },
            {"ip.http.port" },
            {"ip.https.enable" },
            {"ip.https.port" },
            {"ip.lpd.enable" },
            {"ip.mac_raw" },
            {"ip.mirror.appl_path" },
            {"ip.mirror.auto" },
            {"ip.mirror.error_retry" },
            {"ip.mirror.feedback.auto" },
            {"ip.mirror.feedback.freq" },
            {"ip.mirror.feedback.odometer" },
            {"ip.mirror.feedback.path" },
            {"ip.mirror.freq" },
            {"ip.mirror.freq_hours" },
            {"ip.mirror.interface" },
            {"ip.mirror.last_error" },
            {"ip.mirror.last_time" },
            {"ip.mirror.mode" },
            {"ip.mirror.password" },
            {"ip.mirror.path" },
            {"ip.mirror.reset_delay" },
            {"ip.mirror.server" },
            {"ip.mirror.success" },
            {"ip.mirror.success_time" },
            {"ip.mirror.username" },
            {"ip.mirror.version" },
            {"ip.netmask" },
            {"ip.ntp.enable" },
            {"ip.ntp.log" },
            {"ip.ntp.servers" },
            {"ip.ping_gateway_interval" },
            {"ip.pop3.enable" },
            {"ip.pop3.password" },
            {"ip.pop3.poll" },
            {"ip.pop3.print_body" },
            {"ip.pop3.print_headers" },
            {"ip.pop3.save_attachments" },
            {"ip.pop3.server_addr" },
            {"ip.pop3.username" },
            {"ip.pop3.verbose_headers" },
            {"ip.port" },
            {"ip.port_alternate" },
            {"ip.port_json_config" },
            {"ip.port_single_conn" },
            {"ip.port_single_conn_idle_timeout" },
            {"ip.primary_network" },
            {"ip.smtp.domain" },
            {"ip.smtp.enable" },
            {"ip.smtp.server_addr" },
            {"ip.snmp.enable" },
            {"ip.snmp.get_community_name" },
            {"ip.snmp.set_community_name" },
            {"ip.snmp.trap_community_name" },
            {"ip.tcp.enable" },
            {"ip.tcp.nagle_algorithm" },
            {"ip.telnet.enable" },
            {"ip.telnet.enable" },
            {"ip.tls.enable" },
            {"ip.tls.port" },
            {"ip.tls.port_json_config" },
            {"ip.udp.enable" },
            {"log.reboot.code" },
            {"log.reboot.codes" },
            {"log.reboot.reason" },
            {"log.reboot.report" },
            {"mcr.crypt.algorithm" },
            {"mcr.crypt.enabled" },
            {"mcr.crypt.key_mgmt" },
            {"mcr.revision" },
            {"media.bar_location" },
            {"media.cartridge.darkness" },
            {"media.cartridge.inserted" },
            {"media.cartridge.labels_remaining" },
            {"media.cartridge.length" },
            {"media.cartridge.part_number" },
            {"media.cartridge.speed" },
            {"media.cartridge.total_label_cnt" },
            {"media.cartridge.width" },
            {"media.draft_mode" },
            {"media.dynamic_length_calibration" },
            {"media.feed_skip" },
            {"media.media_low.external" },
            {"media.media_low.warning" },
            {"media.part_number" },
            {"media.present.cut_amount" },
            {"media.present.loop_length_max" },
            {"memory.flash_size" },
            {"memory.ram_free" },
            {"memory.ram_size" },
            {"netmanage.avalanche.agent_addr" },
            {"netmanage.avalanche.available_agent" },
            {"netmanage.avalanche.available_port" },
            {"netmanage.avalanche.encryption_type" },
            {"netmanage.avalanche.interval" },
            {"netmanage.avalanche.interval_update" },
            {"netmanage.avalanche.model_name" },
            {"netmanage.avalanche.set_property" },
            {"netmanage.avalanche.startup_update" },
            {"netmanage.avalanche.tcp_connection_timeout" },
            {"netmanage.avalanche.terminal_id" },
            {"netmanage.avalanche.text_msg.beep" },
            {"netmanage.avalanche.text_msg.display" },
            {"netmanage.avalanche.text_msg.print" },
            {"netmanage.avalanche.udp_timeout" },
            {"netmanage.error_code" },
            {"netmanage.state_code" },
            {"netmanage.status_code" },
            {"odometer.cut_marker_count" },
            {"odometer.headclean" },
            {"odometer.headnew" },
            {"odometer.label_dot_length" },
            {"odometer.latch_open_count" },
            {"odometer.media_marker_count" },
            {"odometer.media_marker_count1" },
            {"odometer.media_marker_count2" },
            {"odometer.retracts_count" },
            {"odometer.rfid.valid_resettable" },
            {"odometer.rfid.void_resettable" },
            {"odometer.total_cuts" },
            {"odometer.total_label_count" },
            {"odometer.total_print_length" },
            {"odometer.user_label_count" },
            {"odometer.user_label_count1" },
            {"odometer.user_label_count2" },
            {"odometer.user_total_cuts" },
            {"parallel_port.mode" },
            {"parallel_port.present" },
            {"power.average_current" },
            {"power.battery_led_blink_rate" },
            {"power.battery_led_enable" },
            {"power.battery_led_off_duration" },
            {"power.battery_led_on_duration" },
            {"power.battery_type" },
            {"power.current" },
            {"power.cycle_count" },
            {"power.dtr_power_off" },
            {"power.energy_star.enable" },
            {"power.energy_star.timeout" },
            {"power.label_queue.shutdown" },
            {"power.part_number" },
            {"power.percent_health" },
            {"power.power_on_mode" },
            {"power.remaining_capacity" },
            {"power.sleep.cradle" },
            {"power.temperature" },
            {"power.temperature25.40 C" },
            {"power.voltage" },
            {"power.wake.radio" },
            {"print.legacy_compatibility" },
            {"print.tone" },
            {"print.troubleshooting_label_print" },
            {"relative_darkness" },
            {"rfid.adaptive_antenna" },
            {"rfid.country_code" },
            {"rfid.error.response" },
            {"rfid.hop_table_version" },
            {"rfid.log.enabled" },
            {"rfid.log.entries" },
            {"rfid.position.program" },
            {"rfid.reader_1.antenna_port" },
            {"rfid.reader_1.firmware_version" },
            {"rfid.reader_1.hardware_version" },
            {"rfid.reader_1.model" },
            {"rfid.reader_1.power.single_power" },
            {"rfid.recipe_version" },
            {"rfid.region_code" },
            {"rfid.tag.read.content" },
            {"rfid.tag.read.result_line1" },
            {"rfid.tag.read.result_line2_alternate" },
            {"rfid.tag.test.content" },
            {"rfid.tag.type" },
            {"ribbon.cartridge.authenticated" },
            {"ribbon.cartridge.inserted" },
            {"ribbon.cartridge.length" },
            {"ribbon.cartridge.length_remaining" },
            {"ribbon.cartridge.part_number" },
            {"ribbon.part_number" },
            {"ribbon.serial_number" },
            {"rtc.timezone" },
            {"rtc.unix_timestamp" },
            {"sensor.back_bar.brightness" },
            {"sensor.back_bar.cur" },
            {"sensor.back_bar.offset" },
            {"sensor.back_bar.ppr_out_thold" },
            {"sensor.battery.in_volts" },
            {"sensor.cover_open" },
            {"sensor.front_bar.brightness" },
            {"sensor.front_bar.cur" },
            {"sensor.front_bar.gain" },
            {"sensor.front_bar.offset" },
            {"sensor.front_bar.paper_out_threshold" },
            {"sensor.front_bar.thold" },
            {"sensor.gap.brightness" },
            {"sensor.gap.gain" },
            {"sensor.gap.offset" },
            {"sensor.gap.thold" },
            {"sensor.head.temp" },
            {"sensor.head.temp_avg" },
            {"sensor.head.temp_celsius" },
            {"sensor.paper_supply" },
            {"sensor.peel.brightness" },
            {"sensor.peel.gain" },
            {"sensor.peel.thold" },
            {"sensor.peeler" },
            {"sensor.self_adjusting_enable" },
            {"sensor.width.cur" },
            {"sensor.width.in_dots" },
            {"usb.device.device_id_string" },
            {"usb.device.device_unique_id" },
            {"usb.device.device_version" },
            {"usb.device.manufacturer_string" },
            {"usb.device.product_id" },
            {"usb.device.product_string" },
            {"usb.device.serial_string" },
            {"usb.device.vendor_id" },
            {"usb.halt" },
            {"usb.host.fn_field_data" },
            {"usb.host.fn_last_field" },
            {"usb.host.hid_count" },
            {"usb.host.keyboard_input" },
            {"usb.host.lock_out" },
            {"usb.host.mass_storage_count" },
            {"usb.host.read_list_print_delay" },
            {"usb.host.template_list" },
            {"usb.host.template_print_amount" },
            {"usb.host.write_list" },
            {"usb.mirror.appl_path" },
            {"usb.mirror.auto" },
            {"usb.mirror.enable" },
            {"usb.mirror.enabled" },
            {"usb.mirror.error_retry" },
            {"usb.mirror.feedback.auto" },
            {"usb.mirror.feedback.odometer" },
            {"usb.mirror.feedback.path" },
            {"usb.mirror.last_error" },
            {"usb.mirror.last_time" },
            {"usb.mirror.path" },
            {"usb.mirror.reset_delay" },
            {"usb.mirror.success" },
            {"usb.mirror.success_time.fm" },
            {"usbusb.host.read_list" },
            {"weblink.cloud_connect.enable" },
            {"weblink.enable" },
            {"weblink.ip.conn1.authentication.entries" },
            {"weblink.ip.conn1.location" },
            {"weblink.ip.conn1.maximum_simultaneous_connections" },
            {"weblink.ip.conn1.num_connections" },
            {"weblink.ip.conn1.proxy" },
            {"weblink.ip.conn1.retry_interval" },
            {"weblink.ip.conn1.test.location" },
            {"weblink.ip.conn1.test.retry_interval" },
            {"weblink.ip.conn1.test.test_on" },
            {"weblink.ip.conn2.authentication.entries" },
            {"weblink.ip.conn2.location" },
            {"weblink.ip.conn2.maximum_simultaneous_connections" },
            {"weblink.ip.conn2.num_connections" },
            {"weblink.ip.conn2.proxy" },
            {"weblink.ip.conn2.retry_interval" },
            {"weblink.ip.conn2.test.location" },
            {"weblink.ip.conn2.test.retry_interval" },
            {"weblink.ip.conn2.test.test_on" },
            {"weblink.ip.conn[1|2].retry_interval_random_max" },
            {"weblink.logging.entries" },
            {"weblink.logging.max_entries" },
            {"weblink.printer_reset_required" },
            {"weblink.zebra_connector.authentication.entries" },
            {"weblink.zebra_connector.enable" },
            {"weblink.zebra_connector.proxy" },
            {"weblink.zebra_connector.version" },
            {"wep.key_format" },
            {"wlan.11ac.80mhz_enable" },
            {"wlan.11d.enable" },
            {"wlan.11n.20mhz_only" },
            {"wlan.11n.aggregation" },
            {"wlan.11n.greenfield" },
            {"wlan.11n.rifs" },
            {"wlan.11n.short_gi_20mhz" },
            {"wlan.11n.short_gi_40mhz" },
            {"wlan.8021x.authentication" },
            {"wlan.8021x.eap.password" },
            {"wlan.8021x.eap.privkey_password" },
            {"wlan.8021x.eap.username" },
            {"wlan.8021x.enable" },
            {"wlan.8021x.peap.anonymous_identity" },
            {"wlan.8021x.peap.peap_username" },
            {"wlan.8021x.peap.privkey_password" },
            {"wlan.8021x.validate_peap_server_certificate" },
            {"wlan.active_channels" },
            {"wlan.adhoc_last_channel" },
            {"wlan.adhocautomode" },
            {"wlan.adhocchannel" },
            {"wlan.allowed_band" },
            {"wlan.associated" },
            {"wlan.auth_type" },
            {"wlan.authenticated" },
            {"wlan.authentication_error" },
            {"wlan.available" },
            {"wlan.band_preference" },
            {"wlan.bssid" },
            {"wlan.channel" },
            {"wlan.channel_mask" },
            {"wlan.country_code" },
            {"wlan.current_tx_rate" },
            {"wlan.enable" },
            {"wlan.encryption_index" },
            {"wlan.encryption_key1" },
            {"wlan.encryption_key2" },
            {"wlan.encryption_key3" },
            {"wlan.encryption_key4" },
            {"wlan.encryption_mode" },
            {"wlan.essid" },
            {"wlan.firmware_version" },
            {"wlan.ip.addr" },
            {"wlan.ip.arp_interval" },
            {"wlan.ip.default_addr_enable" },
            {"wlan.ip.dhcp.arp_verify" },
            {"wlan.ip.dhcp.cache_ip" },
            {"wlan.ip.dhcp.cid_all" },
            {"wlan.ip.dhcp.cid_enable" },
            {"wlan.ip.dhcp.cid_prefix" },
            {"wlan.ip.dhcp.cid_suffix" },
            {"wlan.ip.dhcp.cid_type" },
            {"wlan.ip.dhcp.lease.last_attempt" },
            {"wlan.ip.dhcp.lease.length" },
            {"wlan.ip.dhcp.lease.server" },
            {"wlan.ip.dhcp.lease.time_left" },
            {"wlan.ip.dhcp.option12" },
            {"wlan.ip.dhcp.option12_format" },
            {"wlan.ip.dhcp.option12_value" },
            {"wlan.ip.dhcp.request_timeout" },
            {"wlan.ip.dhcp.requests_per_session" },
            {"wlan.ip.dhcp.session_interval" },
            {"wlan.ip.dns.servers" },
            {"wlan.ip.gateway" },
            {"wlan.ip.netmask" },
            {"wlan.ip.port" },
            {"wlan.ip.port_alternate" },
            {"wlan.ip.port_json_config" },
            {"wlan.ip.protocol" },
            {"wlan.ip.timeout.enable" },
            {"wlan.ip.timeout.value" },
            {"wlan.ip.wins.addr" },
            {"wlan.ip.wins.permanent_source" },
            {"wlan.keep_alive.enable" },
            {"wlan.keep_alive.timeout" },
            {"wlan.kerberos.kdc" },
            {"wlan.kerberos.mode" },
            {"wlan.kerberos.password" },
            {"wlan.kerberos.realm" },
            {"wlan.kerberos.username" },
            {"wlan.leap_mode" },
            {"wlan.leap_username" },
            {"wlan.mac_addr" },
            {"wlan.mac_raw" },
            {"wlan.operating_mode" },
            {"wlan.password" },
            {"wlan.permitted_channels" },
            {"wlan.pmf" },
            {"wlan.roam.monitor" },
            {"wlan.roam.signal" },
            {"wlan.signal_noise" },
            {"wlan.signal_quality" },
            {"wlan.signal_strength" },
            {"wlan.station_name" },
            {"wlan.tx_power" },
            {"wlan.tx_rate" },
            {"wlan.user_channel_list" },
            {"wlan.username" },
            {"wlan.waveagent.enable" },
            {"wlan.waveagent.udp_port" },
            {"wlan.wep.auth_type" },
            {"wlan.wep.index" },
            {"wlan.wep.key1" },
            {"wlan.wep.key2" },
            {"wlan.wep.key3" },
            {"wlan.wep.key4" },
            {"wlan.wpa.groupkey_ciphersuite" },
            {"wlan.wpa.pairwise_ciphersuite" },
            {"wlan.wpa.psk" },
            {"wlan.wpa.timecheck" },
            {"zbi.control.line_number" },
            {"zbi.control.variable_name" },
            {"zbi.control.variable_value" },
            {"zbi.enable" },
            {"zbi.key" },
            {"zbi.last_error" },
            {"zbi.program_list" },
            {"zbi.revision" },
            {"zbi.running_program_name" },
            {"zbi.start_info.file_name" },
            {"zbi.start_info.memory_alloc" },
            {"zbi.state" },
            {"zpl.caret" },
            {"zpl.control_character" },
            {"zpl.delimiter" },
            {"zpl.format_prefix" },
            {"zpl.label_length" },
            {"zpl.left_position" },
            {"zpl.system_error" },
            {"zpl.system_status" },
            {"zpl.zpl_mode" },
        };

        public static List<String> SetVarCommands = new List<String>()
        {
            {"alerts.add [condition],[destination],[set],[clear],[destination_address],[port],[quelling],[SGD_name]" },
            {"alerts.configured <a '|' delimited list of configured alerts>" },
            {"alerts.http.authentication.add servername[ username][ password]" },
            {"alerts.http.authentication.remove servername" },
            {"alerts.http.logging.clear value" },
            {"alerts.http.proxy http://username:password@mydomain.com:3128/" },
            {"alerts.tracked_settings.clear_log value" },
            {"alerts.tracked_settings.log_tracked settings.name1,settings.name2..." },
            {"alerts.tracked_settings.max_log_entries value" },
            {"alerts.tracked_settings.zbi_notified" },
            {"alerts.tracked_sgds.max_log_entries value" },
            {"apl.enable value" },
            {"bluetooth.afh_map value" },
            {"bluetooth.afh_mode value" },
            {"bluetooth.authentication value" },
            {"bluetooth.bluetooth_pin value" },
            {"bluetooth.discoverable value" },
            {"bluetooth.enable on" },
            {"bluetooth.enable" },
            {"bluetooth.enable_reconnect value" },
            {"bluetooth.friendly_name value" },
            {"bluetooth.json_config_channel_enable value" },
            {"bluetooth.le.controller_mode value" },
            {"bluetooth.le.minimum_security value" },
            {"bluetooth.le.power_class value" },
            {"bluetooth.minimum_security_mode value" },
            {"bluetooth.page_scan_window value" },
            {"bluetooth.power_class value" },
            {"capture.channel1.delimiter delimiter" },
            {"capture.channel1.max_length value" },
            {"capture.channel1.port value" },
            {"comm.baud value" },
            {"comm.halt value" },
            {"comm.parity value" },
            {"comm.pnp_option value" },
            {"comm.stop_bits value" },
            {"comm.type value" },
            {"cradle.comm.baud value" },
            {"cradle.comm.handshake value" },
            {"cutter.clean_cutter on" },
            {"cutter.clean_cutter" },
            {"device.allow_firmware_downloads value" },
            {"device.allow_non_display_numeric_comparison value" },
            {"device.applicator.data_ready value" },
            {"device.applicator.data_ready_activation value" },
            {"device.applicator.end_print value" },
            {"device.applicator.error_on_pause value" },
            {"device.applicator.feed value" },
            {"device.applicator.media_out value" },
            {"device.applicator.pause value" },
            {"device.applicator.reprint value" },
            {"device.applicator.rfid_void value" },
            {"device.applicator.ribbon_low value" },
            {"device.applicator.ribbon_out" },
            {"device.applicator.service_required value" },
            {"device.applicator.start_print value" },
            {"device.applicator.start_print_mode value" },
            {"device.applicator.voltage value" },
            {"device.command_override.active value" },
            {"device.command_override.add command" },
            {"device.command_override.clear value" },
            {"device.company_contact value" },
            {"device.download_connection_timeout value" },
            {"device.epl_legacy_mode value" },
            {"device.friendly_name value" },
            {"device.frontpanel.feedenabled no" },
            {"device.frontpanel.feedenabled" },
            {"device.frontpanel.key_press A" },
            {"device.frontpanel.key_press" },
            {"device.frontpanel.line1 value" },
            {"device.frontpanel.line2 value" },
            {"device.idle_display_format value" },
            {"device.internal_wired_setting_location value" },
            {"device.languages value" },
            {"device.light.cover_open_brightness value" },
            {"device.light.head_open_brightness value" },
            {"device.light.media_path_brightness value" },
            {"device.light.ribbon_path_brightness value" },
            {"device.location value" },
            {"device.orientation value" },
            {"device.pause " },
            {"device.pnp_option value" },
            {"device.position.accuracy value" },
            {"device.position.altitude value" },
            {"device.position.latitude value" },
            {"device.position.longitude value" },
            {"device.print_2key " },
            {"device.print_reprogram_2key value" },
            {"device.prompted_default_network value" },
            {"device.prompted_network_reset value" },
            {"device.prompted_reset value" },
            {"device.reset " },
            {"device.restore_defaults value" },
            {"device.save_2key value" },
            {"device.sensor_profile value" },
            {"device.sensor_select value" },
            {"device.set_clock_to_build_date value" },
            {"device.syslog.clear_log " },
            {"device.syslog.configuration value" },
            {"device.syslog.configuration" },
            {"device.syslog.enable value" },
            {"device.syslog.log_max_file_size value" },
            {"device.syslog.save_local_file value" },
            {"device.user_p1 value" },
            {"device.user_p2 value" },
            {"device.user_vars.create name:type:range:defaultValue" },
            {"device.user_vars.set_range name:type:range" },
            {"device.user_vars.userVar1 2" },
            {"device.xml.enable on" },
            {"display.backlight value" },
            {"display.backlight_on_time time" },
            {"display.batch_counter value" },
            {"display.bluetooth.mac on" },
            {"display.calibrate " },
            {"display.language language" },
            {"display.load_card value" },
            {"display.password.level value" },
            {"display.root_wml value" },
            {"dsplay.language dutch" },
            {"encryption_index 1" },
            {"evice.cpcl_synchronous_mode value" },
            {"external_wired.check value" },
            {"external_wired.ip.addr value" },
            {"external_wired.ip.arp_interval value" },
            {"external_wired.ip.default_addr_enable value" },
            {"external_wired.ip.dhcp.cid_all value" },
            {"external_wired.ip.dhcp.cid_enable value" },
            {"external_wired.ip.dhcp.cid_prefix value" },
            {"external_wired.ip.dhcp.cid_suffix value" },
            {"external_wired.ip.dhcp.cid_type value" },
            {"external_wired.ip.gateway value" },
            {"external_wired.ip.netmask value" },
            {"external_wired.ip.port value" },
            {"external_wired.ip.protocol value" },
            {"external_wired.ip.timeout.enable value" },
            {"external_wired.ip.timeout.value value" },
            {"ezpl.head_close_action value" },
            {"ezpl.label_length_max 6.2" },
            {"ezpl.label_length_max value" },
            {"ezpl.label_sensor value" },
            {"ezpl.manual_calibration " },
            {"ezpl.media_type value" },
            {"ezpl.power_up_action value" },
            {"ezpl.print_method direct thermal" },
            {"ezpl.print_method value" },
            {"ezpl.print_width value" },
            {"ezpl.reprint_mode value" },
            {"ezpl.take_label value" },
            {"ezpl.tear_off value" },
            {"file.capture_response.destination usb_file" },
            {"file.dir value" },
            {"file.dir_format value" },
            {"file.run values" },
            {"file.type value" },
            {"formats.cancel_all " },
            {"head.darkness_switch_enable value" },
            {"input.capture value" },
            {"interface.network.active.wins.addr 10.3.5.120" },
            {"interface.network.active.wins_addr value" },
            {"internal_wired.8021x.password value" },
            {"internal_wired.8021x.peap.anonymous_identity value" },
            {"internal_wired.8021x.peap.validate_server_certificate value" },
            {"internal_wired.8021x.private_key_password value" },
            {"internal_wired.8021x.security none" },
            {"internal_wired.8021x.ttls_tunnel value" },
            {"internal_wired.8021x.username value" },
            {"internal_wired.activity_led value" },
            {"internal_wired.auto_switchover value" },
            {"internal_wired.enable value" },
            {"internal_wired.ip.addr value" },
            {"internal_wired.ip.arp_interval value" },
            {"internal_wired.ip.default_addr_enable value" },
            {"internal_wired.ip.dhcp.arp_verify value" },
            {"internal_wired.ip.dhcp.cache_ip value" },
            {"internal_wired.ip.dhcp.cid_all value" },
            {"internal_wired.ip.dhcp.cid_enable value" },
            {"internal_wired.ip.dhcp.cid_prefix value" },
            {"internal_wired.ip.dhcp.cid_suffix value" },
            {"internal_wired.ip.dhcp.cid_type value" },
            {"internal_wired.ip.dhcp.option12 value" },
            {"internal_wired.ip.dhcp.option12_format value" },
            {"internal_wired.ip.dhcp.requests_per_session value" },
            {"internal_wired.ip.gateway value" },
            {"internal_wired.ip.netmask value" },
            {"internal_wired.ip.port value" },
            {"internal_wired.ip.port_alternate value" },
            {"internal_wired.ip.port_alternate" },
            {"internal_wired.ip.port_json_config value" },
            {"internal_wired.ip.protocol value" },
            {"internal_wired.ip.timeout.enable value" },
            {"internal_wired.ip.timeout.value value" },
            {"internal_wired.ip.wins.addr value" },
            {"internal_wired.ip.wins.permanent_source value" },
            {"ip.addr value" },
            {"ip.arp_interval value" },
            {"ip.bootp.enable value" },
            {"ip.dhcp.arp_verify value" },
            {"ip.dhcp.auto_provision_enable value" },
            {"ip.dhcp.cache_ip value" },
            {"ip.dhcp.cid_all value" },
            {"ip.dhcp.cid_enable value" },
            {"ip.dhcp.cid_prefix value" },
            {"ip.dhcp.cid_suffix value" },
            {"ip.dhcp.cid_type value" },
            {"ip.dhcp.cid_value value" },
            {"ip.dhcp.enable value" },
            {"ip.dhcp.ntp.enable value" },
            {"ip.dhcp.option12 value" },
            {"ip.dhcp.option12_format value" },
            {"ip.dhcp.request_timeout value" },
            {"ip.dhcp.requests_per_session value" },
            {"ip.dhcp.session_interval value" },
            {"ip.dhcp.user_class_id value" },
            {"ip.dhcp.vendor_class_id value" },
            {"ip.firewall.whitelist_in value" },
            {"ip.ftp.enable value" },
            {"ip.ftp.execute_file value" },
            {"ip.ftp.request_password value" },
            {"ip.gateway value" },
            {"ip.http.admin_name value" },
            {"ip.http.admin_password value" },
            {"ip.http.custom_link_name value" },
            {"ip.http.custom_link_url value" },
            {"ip.http.enable value" },
            {"ip.http.faq_url value" },
            {"ip.http.port value" },
            {"ip.https.enable value" },
            {"ip.https.port value" },
            {"ip.lpd.enable value" },
            {"ip.mirror.appl_path values" },
            {"ip.mirror.auto values" },
            {"ip.mirror.error_retry value" },
            {"ip.mirror.feedback.auto value" },
            {"ip.mirror.feedback.freq value" },
            {"ip.mirror.feedback.odometer values" },
            {"ip.mirror.feedback.path value" },
            {"ip.mirror.fetch " },
            {"ip.mirror.freq value" },
            {"ip.mirror.freq_hours values" },
            {"ip.mirror.interface value" },
            {"ip.mirror.mode values" },
            {"ip.mirror.password value" },
            {"ip.mirror.path value" },
            {"ip.mirror.reset_delay value" },
            {"ip.mirror.server value" },
            {"ip.mirror.username value" },
            {"ip.netmask value" },
            {"ip.ntp.enable value" },
            {"ip.ntp.servers value" },
            {"ip.ping_gateway_interval value" },
            {"ip.pop3.enable value" },
            {"ip.pop3.password value" },
            {"ip.pop3.poll value" },
            {"ip.pop3.print_body value" },
            {"ip.pop3.print_headers value" },
            {"ip.pop3.save_attachments value" },
            {"ip.pop3.server_addr value" },
            {"ip.pop3.username value" },
            {"ip.pop3.verbose_headers value" },
            {"ip.port value" },
            {"ip.port_alternate value" },
            {"ip.port_json_config value" },
            {"ip.port_single_conn value" },
            {"ip.port_single_conn_idle_timeout value" },
            {"ip.primary_network value" },
            {"ip.smtp.domain value" },
            {"ip.smtp.enable value" },
            {"ip.smtp.server_addr value" },
            {"ip.snmp.enable value" },
            {"ip.snmp.get_community_name value" },
            {"ip.snmp.set_community_name value" },
            {"ip.snmp.trap_community_name public" },
            {"ip.tcp.enable value" },
            {"ip.tcp.nagle_algorithm value" },
            {"ip.telnet.enable value" },
            {"ip.tls.enable value" },
            {"ip.tls.port value" },
            {"ip.tls.port_json_config value" },
            {"ip.udp.enable value" },
            {"mcr.cancel " },
            {"mcr.out value" },
            {"media.bar_location value" },
            {"media.cut_now " },
            {"media.darkness_mode value" },
            {"media.draft_mode value" },
            {"media.feed_skip value" },
            {"media.media_low.warning value" },
            {"media.part_number value" },
            {"media.present.cut_amount value" },
            {"media.present.loop_length value" },
            {"media.present.loop_length_max value" },
            {"media.printmode T" },
            {"media.serial_number A34567BC6789" },
            {"media.speed 2" },
            {"netmanage.avalanche.agent_addr value" },
            {"netmanage.avalanche.available_port value" },
            {"netmanage.avalanche.encryption_type value" },
            {"netmanage.avalanche.interval value" },
            {"netmanage.avalanche.interval_update value" },
            {"netmanage.avalanche.model_name value" },
            {"netmanage.avalanche.set_property ZebraLocation=VH" },
            {"netmanage.avalanche.set_property value" },
            {"netmanage.avalanche.startup_update value" },
            {"netmanage.avalanche.tcp_connection_timeout value" },
            {"netmanage.avalanche.terminal_id value" },
            {"netmanage.avalanche.text_msg.beep value" },
            {"netmanage.avalanche.text_msg.display value" },
            {"netmanage.avalanche.text_msg.print value" },
            {"netmanage.avalanche.udp_timeout value" },
            {"odometer.cut_marker_count value" },
            {"odometer.headclean value" },
            {"odometer.headnew value" },
            {"odometer.latch_open_count value" },
            {"odometer.media_marker_count value" },
            {"odometer.media_marker_count1 value" },
            {"odometer.media_marker_count2 value" },
            {"odometer.retracts_count value" },
            {"odometer.rfid.valid_resettable value" },
            {"odometer.rfid.void_resettable value" },
            {"odometer.user_label_count value" },
            {"odometer.user_label_count1 value" },
            {"odometer.user_label_count2 value" },
            {"odometer.user_total_cuts 0" },
            {"parallel_port.mode value" },
            {"power.battery_led_blink_rate value" },
            {"power.battery_led_enable value" },
            {"power.battery_led_off_duration value" },
            {"power.battery_led_on_duration value" },
            {"power.dtr_power_off value" },
            {"power.energy_star.enable value" },
            {"power.energy_star.timeout value" },
            {"power.label_queue.shutdown value" },
            {"power.sleep.cradle values" },
            {"power.wake.radio values" },
            {"print.legacy_compatibility value" },
            {"print.tone value" },
            {"print.troubleshooting_label_print value" },
            {"rfid.adaptive_antenna value" },
            {"rfid.antenna_sweep value" },
            {"rfid.country_code value" },
            {"rfid.enable value" },
            {"rfid.log.clear " },
            {"rfid.log.enabled value" },
            {"rfid.position.program value" },
            {"rfid.reader_1.antenna_port value" },
            {"rfid.reader_1.power.read 16" },
            {"rfid.reader_1.power.single_power value" },
            {"rfid.reader_1.power.write 16" },
            {"rfid.tag.calibrate value" },
            {"rfid.tag.data" },
            {"rfid.tag.read.content value" },
            {"rfid.tag.read.execute" },
            {"rfid.tag.read.result_line1_alternate" },
            {"rfid.tag.read.result_line2" },
            {"rfid.tag.test value" },
            {"rfid.tag.test.content value" },
            {"rfid.tag.test.execute" },
            {"rfid.tag.test.result_line1" },
            {"rfid.tag.test.result_line2" },
            {"rfid.tag.type value" },
            {"ribbon.part_number value" },
            {"ribbon.serial_number value" },
            {"rtc.timezone value" },
            {"rtc.unix_timestamp 123123" },
            {"sensor.self_adjusting_enable value" },
            {"usb.device.device_unique_id value" },
            {"usb.halt value" },
            {"usb.host.config_info_to_usb values" },
            {"usb.host.fn_field_data value" },
            {"usb.host.keyboard_input" },
            {"usb.host.lock_out value" },
            {"usb.host.read_list value" },
            {"usb.host.read_list_print_delay" },
            {"usb.host.template_print_amount value" },
            {"usb.host.write_list value" },
            {"usb.mirror.appl_path path" },
            {"usb.mirror.auto value" },
            {"usb.mirror.enable value" },
            {"usb.mirror.enabled value" },
            {"usb.mirror.error_retry value" },
            {"usb.mirror.feedback.auto value" },
            {"usb.mirror.feedback.odometer value" },
            {"usb.mirror.feedback.path value" },
            {"usb.mirror.reset_delay" },
            {"weblink.cloud_connect.enable value" },
            {"weblink.ip.conn1.authentication.add servername[ username][ password]" },
            {"weblink.ip.conn1.authentication.remove servername" },
            {"weblink.ip.conn1.authentication.remove" },
            {"weblink.ip.conn1.location value" },
            {"weblink.ip.conn1.maximum_simultaneous_connections value" },
            {"weblink.ip.conn1.proxy url" },
            {"weblink.ip.conn1.retry_interval value" },
            {"weblink.ip.conn1.test.location url" },
            {"weblink.ip.conn1.test.retry_interval value" },
            {"weblink.ip.conn1.test.test_on value" },
            {"weblink.ip.conn2.authentication.add servername[ username][ password]" },
            {"weblink.ip.conn2.authentication.remove servername" },
            {"weblink.ip.conn2.location value" },
            {"weblink.ip.conn2.location" },
            {"weblink.ip.conn2.maximum_simultaneous_connections value" },
            {"weblink.ip.conn2.proxy url" },
            {"weblink.ip.conn2.retry_interval value" },
            {"weblink.ip.conn2.test.location url" },
            {"weblink.ip.conn2.test.retry_interval value" },
            {"weblink.ip.conn2.test.test_on value" },
            {"weblink.ip.conn[1].retry_interval_random_max 120" },
            {"weblink.ip.conn[1|2].retry_interval_random_max value" },
            {"weblink.ip.conn[2].retry_interval_random_max 60" },
            {"weblink.logging.clear value" },
            {"weblink.logging.max_entries value" },
            {"weblink.restore_defaults value" },
            {"weblink.zebra_connector.authentication.add server username password" },
            {"weblink.zebra_connector.authentication.add" },
            {"weblink.zebra_connector.authentication.remove server" },
            {"weblink.zebra_connector.enable value" },
            {"weblink.zebra_connector.proxy url" },
            {"weblink.zebra_connector.proxy" },
            {"wlan.11ac.80mhz_enable value" },
            {"wlan.11d.enable value" },
            {"wlan.11n.20mhz_only value" },
            {"wlan.11n.aggregation value" },
            {"wlan.11n.greenfield value" },
            {"wlan.11n.rifs value" },
            {"wlan.11n.short_gi_20mhz value" },
            {"wlan.11n.short_gi_40mhz value" },
            {"wlan.8021x.authentication value" },
            {"wlan.8021x.eap.password password" },
            {"wlan.8021x.eap.privkey_password password" },
            {"wlan.8021x.enable value" },
            {"wlan.8021x.peap.anonymous_identity <value>" },
            {"wlan.8021x.peap.peap_password password" },
            {"wlan.8021x.peap.peap_password" },
            {"wlan.8021x.peap.privkey_password password" },
            {"wlan.8021x.validate_peap_server_certificate value" },
            {"wlan.8021x.validate_peap_server_certificate" },
            {"wlan.adhocautomode value" },
            {"wlan.adhocchannel value" },
            {"wlan.allowed_band value" },
            {"wlan.auth_type value" },
            {"wlan.channel_mask value" },
            {"wlan.country_code value" },
            {"wlan.enable value" },
            {"wlan.encryption_index value" },
            {"wlan.encryption_key1 A1B2C3D4F5" },
            {"wlan.encryption_key2 G1H2J3K4L5" },
            {"wlan.encryption_key3 M1N2P3Q4R5" },
            {"wlan.encryption_key4 S1T2V3W4X5" },
            {"wlan.encryption_key[1|2|3|4] value" },
            {"wlan.encryption_mode value" },
            {"wlan.essid value" },
            {"wlan.ip.addr value" },
            {"wlan.ip.arp_interval value" },
            {"wlan.ip.default_addr_enable value" },
            {"wlan.ip.dhcp.arp_verify value" },
            {"wlan.ip.dhcp.cache_ip off" },
            {"wlan.ip.dhcp.cid_all value" },
            {"wlan.ip.dhcp.cid_enable value" },
            {"wlan.ip.dhcp.cid_prefix value" },
            {"wlan.ip.dhcp.cid_suffix value" },
            {"wlan.ip.dhcp.cid_type value" },
            {"wlan.ip.dhcp.option12 value" },
            {"wlan.ip.dhcp.option12_format value" },
            {"wlan.ip.dhcp.request_timeout value" },
            {"wlan.ip.dhcp.requests_per_session value" },
            {"wlan.ip.dhcp.session_interval value" },
            {"wlan.ip.gateway value" },
            {"wlan.ip.netmask value" },
            {"wlan.ip.port value" },
            {"wlan.ip.port_json_config value" },
            {"wlan.ip.protocol value" },
            {"wlan.ip.timeout.enable value" },
            {"wlan.ip.timeout.value value" },
            {"wlan.ip.wins.addr value" },
            {"wlan.ip.wins.permanent_source value" },
            {"wlan.keep_alive.enable value" },
            {"wlan.keep_alive.timeout value" },
            {"wlan.kerberos.kdc value" },
            {"wlan.kerberos.mode values" },
            {"wlan.kerberos.password value" },
            {"wlan.kerberos.realm value" },
            {"wlan.kerberos.username value" },
            {"wlan.leap_mode values" },
            {"wlan.leap_password password" },
            {"wlan.leap_username values" },
            {"wlan.operating_mode value" },
            {"wlan.password value" },
            {"wlan.pmf value" },
            {"wlan.preamble long" },
            {"wlan.private_key_password password" },
            {"wlan.region_code value" },
            {"wlan.roam.interchannel_delay 400" },
            {"wlan.roam.interval 20" },
            {"wlan.roam.max_chan_scan_time 100" },
            {"wlan.roam.max_fail 30" },
            {"wlan.roam.monitor value" },
            {"wlan.roam.rssid 80" },
            {"wlan.roam.signal value" },
            {"wlan.security value" },
            {"wlan.station_name value" },
            {"wlan.tx_power value" },
            {"wlan.tx_rate value" },
            {"wlan.user_channel_list value" },
            {"wlan.username user" },
            {"wlan.waveagent.enable value" },
            {"wlan.waveagent.udp_port value" },
            {"wlan.wep.auth_type open" },
            {"wlan.wep.index 1" },
            {"wlan.wep.key1 A1B2C3D4F5" },
            {"wlan.wep.key2 112233445566778899" },
            {"wlan.wep.key3 223344556677889900" },
            {"wlan.wep.key4 334455667788990011" },
            {"wlan.wep.key_format hex" },
            {"wlan.wpa.psk 00000000..." },
            {"wlan.wpa.timecheck value" },
            {"zbi.control.add_breakpoint value" },
            {"zbi.control.break " },
            {"zbi.control.clear_breakpoints " },
            {"zbi.control.delete_breakpoint value" },
            {"zbi.control.line_number value" },
            {"zbi.control.restart value" },
            {"zbi.control.run " },
            {"zbi.control.step " },
            {"zbi.control.terminate value" },
            {"zbi.control.variable_name value" },
            {"zbi.control.variable_value value" },
            {"zbi.enable value" },
            {"zbi.program_list value" },
            {"zbi.reseller_key value" },
            {"zbi.start_info.execute choices.bas" },
            {"zbi.start_info.execute" },
            {"zbi.start_info.file_name value" },
            {"zpl.caret value" },
            {"zpl.control_characater 2b" },
            {"zpl.control_character value" },
            {"zpl.delimiter value" },
            {"zpl.format_prefix xx" },
            {"zpl.label_length 1281" },
            {"zpl.label_length value" },
            {"zpl.left_position value" },
            {"zpl.relative_darkness value" },
            {"zpl.system_status zpl" },
            {"zpl.zpl_mode value" },
            {"zpl.zpl_override value" },
        };

        public static List<String> DoCommands = new List<String>()
        {
            { "alerts.add [condition],[destination],[set]," },
            { "alerts.http.authentication.add servername[ username][ password]" },
            { "alerts.http.authentication.remove servername" },
            { "alerts.http.logging.clear value" },
            { "alerts.http.logging.max_entries value" },
            { "alerts.http.proxy http://username:password@mydomain.com:3128/" },
            { "alerts.tracked_settings.clear_log value" },
            { "alerts.tracked_settings.log_tracked settings.name1,settings.name2..." },
            { "alerts.tracked_settings.max_log_entries value" },
            { "bluetooth.clear_bonding_cache" },
            { "device.pause" },
            { "device.print_2key" },
            { "device.restore_defaults value" },
            { "device.syslog.clear_log" },
            { "display.calibrate" },
            { "ezpl.manual_calibration" },
            { "file.delete value" },
            { "file.dir value" },
            { "file.dir_format value" },
            { "file.run value" },
            { "file.type value" },
            { "formats.cancel_all" },
            { "head.element_test" },
            { "ip.mirror.fetch" },
            { "media.cut_now" },
            { "power.shutdown" },
            { "rfid.log.clear" },
            { "usb.mirror.fetch" },
            { "weblink.ip.conn1.proxy url" },
            { "weblink.ip.conn1.retry_interval value" },
            { "weblink.ip.conn1.test.location url" },
            { "weblink.ip.conn1.test.retry_interval value" },
            { "weblink.ip.conn1.test.test_on value" },
            { "weblink.ip.conn2.proxy url" },
            { "weblink.ip.conn2.retry_interval value" },
            { "weblink.ip.conn2.test.location url" },
            { "weblink.ip.conn2.test.retry_interval value" },
            { "weblink.ip.conn2.test.test_on value" },
            { "weblink.logging.clear value" },
            { "weblink.restore_defaults value" },
            { "zpl.calibrate" },
        };
    }
}
